name: Build and Release DotA2-Autoacecpter

on:
  push:
    tags:
      - 'v*'

env:
  TAG_NAME: ${{ github.ref_name }}
  TARGET_VERSION: "${TAG_NAME#'v'}"
  EXPORT_NAME: "dota2-autoaccepter-$TARGET_VERSION"

permissions:
  id-token: write
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install Dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          source Env/bin/activate
          pyinstaller --onefile --add-data "templates:templates" --hidden-import=argparse --name=$EXPORT_NAME autoaccepter/main.py

      - name: Create Executable
        uses: actions/upload-artifact@v4
        with:
          name: dist/$EXPORT_NAME
          path: dist/
          retention-days: 1

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/$EXPORT_NAME
          body: |
            ${{ github.event.head_commit.message }}

